export type Pokemon = {
    Number: string,
    Name: string,
    Type_1: string,
    Type_2: string,
    Total: string,
    HP: string,
    Attack: string,
    Defense: string,
    Sp_Atk: string,
    Sp_Def: string,
    Speed: string,
    Generation: string,
    isLegendary: Boolean,
    Color: String,
    hasGender: Boolean,
    Pr_Male: string,
    Egg_Group_1: string,
    Egg_Group_2: string,
    hasMegaEvolution: true,
    Height_m: string,
    Weight_kg: string,
    Catch_Rate: string,
    Body_Style: string
  };