export type Pokemon = {
    Number: Number,
    Name: string,
    Type_1: string,
    Type_2: string,
    Total: Number,
    HP: Number,
    Attack: Number,
    Defense: Number,
    Sp_Atk: Number,
    Sp_Def: Number,
    Speed: Number,
    Generation: Number,
    isLegendary: Boolean,
    Color: String,
    hasGender: Boolean,
    Pr_Male: Number,
    Egg_Group_1: string,
    Egg_Group_2: string,
    hasMegaEvolution: true,
    Height_m: Number,
    Weight_kg: Number,
    Catch_Rate: Number,
    Body_Style: string
  };